### PR TITLE
Add minimizing steer torque and parallel execution.

### PR DESCRIPTION
**Pull request by moorepants**
I added minimizing steer torque to the objective and it solves in 354 iterations (instead of 1600) and only takes a minute to solve. The steer torques are with +/- 0.5 Nm which is much more realistic. The parallel execution with openmp also speeds up the computation time.

```
 352  4.9960240e-02 5.40e-09 3.66e-05 -11.0 2.34e-03  -2.4 1.00e+00 1.00e+00h  1
 353  4.9961040e-02 5.06e-10 7.29e-05 -11.0 8.75e-04  -2.0 1.00e+00 1.00e+00h  1
 354  4.9963204e-02 1.41e-11 1.99e-04 -11.0 2.62e-03  -2.5 1.00e+00 1.00e+00H  1
Cannot call restoration phase at almost feasible point,
but acceptable point from iteration 135 could be restored.

Number of Iterations....: 354

                                   (scaled)                 (unscaled)
Objective...............:   2.9383639794453770e-02    2.9383639794453770e-02
Dual infeasibility......:   9.6622443386651810e-06    9.6622443386651810e-06
Constraint violation....:   1.3407250484392600e-08    2.9929544353990423e-07
Variable bound violation:   0.0000000000000000e+00    0.0000000000000000e+00
Complementarity.........:   1.0000291185026384e-11    1.0000291185026384e-11
Overall NLP error.......:   9.5770037511635897e-07    9.6622443386651810e-06


Number of objective function evaluations             = 2692
Number of objective gradient evaluations             = 349
Number of equality constraint evaluations            = 2692
Number of inequality constraint evaluations          = 0
Number of equality constraint Jacobian evaluations   = 383
Number of inequality constraint Jacobian evaluations = 0
Number of Lagrangian Hessian evaluations             = 0
Total seconds in IPOPT                               = 64.627

EXIT: Solved To Acceptable Level.
```

### CODE REVIEW

**Comment by moorepants** [comment]
Minimizing steer and drive torques solves in 5 seconds:

```
  83  1.4579592e-03 1.13e-12 4.28e-06 -11.0 4.71e-10    -  1.00e+00 1.00e+00h  1
  84  1.4579592e-03 1.07e-12 3.66e-06 -11.0 1.13e-08    -  1.00e+00 1.00e+00s 22

Number of Iterations....: 84

                                   (scaled)                 (unscaled)
Objective...............:   1.4579591880026159e-03    1.4579591880026159e-03
Dual infeasibility......:   3.6623710593317091e-06    3.6623710593317091e-06
Constraint violation....:   2.7711166694643907e-13    1.0684786388992507e-12
Variable bound violation:   0.0000000000000000e+00    0.0000000000000000e+00
Complementarity.........:   1.0000000000000007e-11    1.0000000000000007e-11
Overall NLP error.......:   3.3398066681552460e-07    3.6623710593317091e-06


Number of objective function evaluations             = 271
Number of objective gradient evaluations             = 86
Number of equality constraint evaluations            = 271
Number of inequality constraint evaluations          = 0
Number of equality constraint Jacobian evaluations   = 86
Number of inequality constraint Jacobian evaluations = 0
Number of Lagrangian Hessian evaluations             = 0
Total seconds in IPOPT                               = 5.383
```

**Comment by moorepants** [comment]
300 nodes and midpoint method gave me:

```
 466  3.3502744e-03 3.91e-12 3.92e-01 -11.0 1.90e-03  -1.7 1.00e+00 1.82e-12h 40
Cannot call restoration phase at point that is almost feasible (violation 3.911094e-12).
Abort in line search due to no other fall back.

Number of Iterations....: 466

                                   (scaled)                 (unscaled)
Objective...............:   3.3502744245825665e-03    3.3502744245825665e-03
Dual infeasibility......:   3.9204435505682317e-01    3.9204435505682317e-01
Constraint violation....:   5.7984089473399484e-13    3.9110936711495015e-12
Variable bound violation:   0.0000000000000000e+00    0.0000000000000000e+00
Complementarity.........:   1.0001586585616293e-11    1.0001586585616293e-11
Overall NLP error.......:   3.1300788761831604e-03    3.9204435505682317e-01


Number of objective function evaluations             = 3935
Number of objective gradient evaluations             = 402
Number of equality constraint evaluations            = 3935
Number of inequality constraint evaluations          = 0
Number of equality constraint Jacobian evaluations   = 500
Number of inequality constraint Jacobian evaluations = 0
Number of Lagrangian Hessian evaluations             = 0
Total seconds in IPOPT                               = 145.487

EXIT: Error in step computation!

```

But that solved with the backward Euler method.

**Comment by brocksam** [comment]
We might need to a back of the envelope calculation/quick inverse dynamics on the solution to the elbow torque problem to check that the muscles are sufficiently strong to produce enough steer torque and steer angle to follow the prescribed path. Could also try with zeroth-order activation dynamics to as that might be easier to solve.

**Comment by moorepants** [comment]
If the parameter values are the same as what we had in the forward sim, we know the muscles can steer the bike.

**Comment by moorepants** [comment]
I got the muscles to solve by removing the instance constraints for u1, u2, u6, u8 (travel speed related). I was getting unusual solutions for T6 before it and the start and ending values seemed suspicious. I think we need a careful review of the instance constraints to check for validity (you can still see odd starting values) and to check whether we need them or not. For tracking problems we may not need lots of instances constraints. Although I did see that if I removed the q1, q2 instance constraints the problem didn't solve.

**Comment by moorepants** [comment]
When I use elbow torques the plot is mislabeled (don't see this on the muscle activation):

image

Not sure why.

**Comment by moorepants** [comment]
I've updated things and muscle driven torque works with the latest sympy master.

**Comment by moorepants** [comment]
This runs for all input sets, so I'm going to merge. We'll need to tweak things further to really improve the OCP definition.

**Comment by moorepants** [comment]
I fixed:

> When I use elbow torques the plot is mislabeled (don't see this on the muscle activation):

in https://github.com/brocksam/muscle-driven-bicycle-paper/commit/958271b4f16ffba6ea0d33b23e04f0f3d3e30a82

**Pull request merged**
