### PR TITLE
Switch from using the derivatives of the holonomic and nonholonomic constraints to using them directly.

### PR DESCRIPTION
**Pull request by moorepants**
@brocksam I think this is all that is needed to enforce the holonomic and nonholonomic constraints directly. No change to opty should be needed.

### CODE REVIEW

**Comment by moorepants** [comment]
This seems to make it through Problem instantiation just fine.

**Comment by moorepants** [comment]
Getting this error:

```
`opty.Problem` instantiated in 205.5569888480004s.
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
File ~/Manuscripts/muscle-driven-bicycle-paper/src/opty_ocp.py:201
    197 # Generate a sensible initial guess
    198 # np.array of length problem.num_free
    199 initial_guess = gen_init_guess_for_opty(model, problem, metadata)
--> 201 pause
    203 # Find the optimal solution.
    204 sol, info = problem.solve(initial_guess)

NameError: name 'pause' is not defined
> /home/moorepants/Manuscripts/muscle-driven-bicycle-paper/src/opty_ocp.py(201)<module>()
    199 initial_guess = gen_init_guess_for_opty(model, problem, metadata)
    200 
--> 201 pause
    202 
    203 # Find the optimal solution.

ipdb> problem.con(initial_guess)
*** ValueError: cannot reshape array of size 2772 into shape (99,14,1)
```

**Comment by moorepants** [comment]
jacobian seems fine though:

```
ipdb> problem.jacobian(initial_guess)
array([ 0.        ,  0.        ,  0.00655345, ..., -1.        ,
        1.        , -1.        ])
ipdb> np.isnan(problem.jacobian(initial_guess))
array([False, False, False, ..., False, False, False])
ipdb> np.any(np.isnan(problem.jacobian(initial_guess)))
False
```

**Comment by brocksam** [comment]
Is this for:

```python
STEER_WITH = SteerWith.STEER_TORQUE
INCLUDE_ROLL_TORQUE = False
```

**Comment by moorepants** [comment]
I just rebased on your branch and ran it. Not sure.

**Comment by brocksam** [comment]
`2772 = 99*14*2`

Is there any more traceback for that error message? I assume it's being thrown within opty?

**Comment by moorepants** [comment]
`problem.con()` isn't the correct method. It is `problem.constraints()`.

**Comment by moorepants** [comment]
Same error though:
```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
File ~/Manuscripts/muscle-driven-bicycle-paper/src/opty_ocp.py:203
    201 problem.objective(initial_guess)
    202 problem.gradient(initial_guess)
--> 203 problem.constraints(initial_guess)
    204 problem.jacobian(initial_guess)
    206 pause

File ~/src/opty/opty/direct_collocation.py:253, in Problem.constraints(self, free)
    229 """Returns the value of the constraint functions given a solution to
    230 the problem.
    231 
   (...)
    250 
    251 """
    252 # This should return a column vector.
--> 253 return self.con(free)

File ~/src/opty/opty/direct_collocation.py:1437, in ConstraintCollocator._wrap_constraint_funcs.<locals>.constraints(free)
   1429 all_specified = self._merge_fixed_free(self.input_trajectories,
   1430                                        self.known_trajectory_map,
   1431                                        free_specified, 'traj')
   1433 all_constants = self._merge_fixed_free(self.parameters,
   1434                                        self.known_parameter_map,
   1435                                        free_constants, 'par')
-> 1437 eom_con_vals = func(free_states, all_specified, all_constants,
   1438                     self.node_time_interval)
   1440 if self.instance_constraints is not None:
   1441     if typ == 'con':

File ~/src/opty/opty/direct_collocation.py:997, in ConstraintCollocator._gen_multi_arg_con_func.<locals>.constraints(state_values, specified_values, constant_values, interval_value)
    992 # TODO : Move this to an attribute of the class so that it is
    993 # only initialized once and just reuse it on each evaluation of
    994 # this function.
    995 result = np.empty((num_constraints, state_values.shape[0]))
--> 997 return f(result, *args).T.flatten()

File ufuncify_matrix_0.pyx:314, in ufuncify_matrix_0.eval_matrix_loop()

ValueError: cannot reshape array of size 2772 into shape (99,14,1)
> /home/moorepants/Manuscripts/muscle-driven-bicycle-paper/ufuncify_matrix_0.pyx(314)ufuncify_matrix_0.eval_matrix_loop()
```

**Comment by moorepants** [comment]
Maybe there is some issue in opty that gets confused if some of the constraint equations do not have derivatives.

**Comment by brocksam** [comment]
> Maybe there is some issue in opty that gets confused if some of the constraint equations do not have derivatives.

This is possible, as I've just checked the code against the previous version that uses the derivatives and it doesn't raise this error.

**Comment by moorepants** [comment]
I just noticed this:

```
ipdb> self.num_states
28
ipdb> me.find_dynamicsymbols(self.eom)
{q14(t), Derivative(u4(t), t), Derivative(u11(t), t), u16(t), Derivative(u2(t), t), Derivative(u5(t), t), q12(t), q7(t), u5(t), u6(t), u3(t), Derivative(u8(t), t), q5(t), Derivative(u14(t), t), q3(t), q15(t), u4(t), Derivative(u7(t), t), u8(t), q13(t), u1(t), Derivative(u12(t), t), Derivative(u13(t), t), Derivative(u6(t), t), T7(t), T6(t), u13(t), u15(t), u2(t), u7(t), q11(t), Derivative(u1(t), t), q16(t), u11(t), q4(t), u14(t), Derivative(u16(t), t), Derivative(u15(t), t), Derivative(u3(t), t), u12(t)}
ipdb> len(self.eom)
14
```

We don't seem to have the q' = u equations present in the equations of motion.

**Comment by moorepants** [comment]
That was the error. It seems to be running now and I'm not hitting the "r" in the ipopt output (yet).

**Comment by moorepants** [comment]
This seemed to have just solved:

image

**Comment by moorepants** [comment]
[first-solution.txt](https://github.com/brocksam/muscle-driven-bicycle-paper/files/12497510/first-solution.txt)

This is the first working solution from the above image. Commit 41b65b08e881d47e9c84

**Pull request merged**
